-- Seed data for ReTech marketplace (30 products)
INSERT INTO public.products (
  title,
  slug,
  category,
  brand,
  model,
  price,
  old_price,
  currency,
  condition,
  storage,
  ram,
  cpu,
  gpu,
  screen_size,
  battery_health,
  color,
  location_city,
  warranty_months,
  description,
  images,
  is_available,
  stock_count,
  rating_avg,
  rating_count
) VALUES
(
  'iPhone 13 Pro 256GB',
  'iphone-13-pro-256gb',
  'smartphones',
  'Apple',
  'iPhone 13 Pro',
  23500,
  27900,
  'UAH',
  'A',
  '256GB',
  NULL,
  NULL,
  NULL,
  '6.1"',
  91,
  'Graphite',
  'Kyiv',
  6,
  'Excellent condition with minor wear on frame. Battery health 91%. Includes box.',
  ARRAY[
    'https://placehold.co/600x600/png?text=iPhone+13+Pro',
    'https://placehold.co/600x600/png?text=iPhone+13+Pro+Back'
  ],
  true,
  3,
  4.8,
  124
),
(
  'Samsung Galaxy S22 128GB',
  'samsung-galaxy-s22-128gb',
  'smartphones',
  'Samsung',
  'Galaxy S22',
  18900,
  22900,
  'UAH',
  'B',
  '128GB',
  NULL,
  NULL,
  NULL,
  '6.1"',
  88,
  'Phantom Black',
  'Lviv',
  3,
  'Great condition with light scratches on back glass. Fully functional.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Galaxy+S22',
    'https://placehold.co/600x600/png?text=Galaxy+S22+Back'
  ],
  true,
  5,
  4.6,
  98
),
(
  'Google Pixel 7 128GB',
  'google-pixel-7-128gb',
  'smartphones',
  'Google',
  'Pixel 7',
  17500,
  NULL,
  'UAH',
  'B',
  '128GB',
  NULL,
  NULL,
  NULL,
  '6.3"',
  92,
  'Obsidian',
  'Kyiv',
  6,
  'Clean device, great camera, small signs of use.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Pixel+7',
    'https://placehold.co/600x600/png?text=Pixel+7+Side'
  ],
  true,
  4,
  4.7,
  65
),
(
  'Xiaomi 12T 256GB',
  'xiaomi-12t-256gb',
  'smartphones',
  'Xiaomi',
  '12T',
  14200,
  16900,
  'UAH',
  'B',
  '256GB',
  NULL,
  NULL,
  NULL,
  '6.67"',
  90,
  'Blue',
  'Odesa',
  3,
  'Solid mid-range phone with fast charging and smooth display.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Xiaomi+12T',
    'https://placehold.co/600x600/png?text=Xiaomi+12T+Back'
  ],
  true,
  6,
  4.4,
  42
),
(
  'OnePlus 9 Pro 256GB',
  'oneplus-9-pro-256gb',
  'smartphones',
  'OnePlus',
  '9 Pro',
  16500,
  19900,
  'UAH',
  'B',
  '256GB',
  NULL,
  NULL,
  NULL,
  '6.7"',
  86,
  'Morning Mist',
  'Dnipro',
  3,
  'Fast and smooth flagship with Hasselblad camera tuning.',
  ARRAY[
    'https://placehold.co/600x600/png?text=OnePlus+9+Pro',
    'https://placehold.co/600x600/png?text=OnePlus+9+Pro+Back'
  ],
  true,
  2,
  4.5,
  37
),
(
  'iPhone SE 2022 64GB',
  'iphone-se-2022-64gb',
  'smartphones',
  'Apple',
  'iPhone SE 2022',
  9900,
  11900,
  'UAH',
  'C',
  '64GB',
  NULL,
  NULL,
  NULL,
  '4.7"',
  83,
  'Starlight',
  'Kharkiv',
  1,
  'Visible wear on frame, screen is clean. Battery health 83%.',
  ARRAY[
    'https://placehold.co/600x600/png?text=iPhone+SE+2022',
    'https://placehold.co/600x600/png?text=iPhone+SE+2022+Back'
  ],
  true,
  7,
  4.2,
  58
),
(
  'MacBook Air M1 8GB/256GB',
  'macbook-air-m1-8gb-256gb',
  'laptops',
  'Apple',
  'MacBook Air M1',
  28900,
  32900,
  'UAH',
  'A',
  '256GB',
  '8GB',
  'Apple M1',
  NULL,
  '13.3"',
  NULL,
  'Space Gray',
  'Kyiv',
  6,
  'Like new, low battery cycles. Perfect for work and study.',
  ARRAY[
    'https://placehold.co/600x600/png?text=MacBook+Air+M1',
    'https://placehold.co/600x600/png?text=MacBook+Air+M1+Side'
  ],
  true,
  4,
  4.9,
  210
),
(
  'Dell XPS 13 9310',
  'dell-xps-13-9310',
  'laptops',
  'Dell',
  'XPS 13 9310',
  26500,
  29900,
  'UAH',
  'B',
  '512GB',
  '16GB',
  'Intel i7-1165G7',
  'Intel Iris Xe',
  '13.4"',
  NULL,
  'Silver',
  'Lviv',
  6,
  'Premium ultrabook with bright display and strong battery life.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Dell+XPS+13',
    'https://placehold.co/600x600/png?text=Dell+XPS+13+Keyboard'
  ],
  true,
  3,
  4.6,
  78
),
(
  'Lenovo ThinkPad T14',
  'lenovo-thinkpad-t14',
  'laptops',
  'Lenovo',
  'ThinkPad T14',
  21900,
  NULL,
  'UAH',
  'B',
  '512GB',
  '16GB',
  'AMD Ryzen 5 PRO',
  'Radeon Graphics',
  '14"',
  NULL,
  'Black',
  'Kyiv',
  3,
  'Business laptop with sturdy build and great keyboard.',
  ARRAY[
    'https://placehold.co/600x600/png?text=ThinkPad+T14',
    'https://placehold.co/600x600/png?text=ThinkPad+T14+Keyboard'
  ],
  true,
  5,
  4.5,
  64
),
(
  'ASUS ROG Zephyrus G14',
  'asus-rog-zephyrus-g14',
  'laptops',
  'ASUS',
  'ROG Zephyrus G14',
  34900,
  38900,
  'UAH',
  'B',
  '1TB',
  '16GB',
  'AMD Ryzen 7 5800HS',
  'NVIDIA RTX 3060',
  '14"',
  NULL,
  'Eclipse Gray',
  'Odesa',
  6,
  'Powerful compact gaming laptop with high refresh display.',
  ARRAY[
    'https://placehold.co/600x600/png?text=ROG+Zephyrus+G14',
    'https://placehold.co/600x600/png?text=ROG+Zephyrus+G14+Top'
  ],
  true,
  2,
  4.7,
  52
),
(
  'HP Spectre x360 13',
  'hp-spectre-x360-13',
  'laptops',
  'HP',
  'Spectre x360',
  23900,
  27900,
  'UAH',
  'B',
  '512GB',
  '16GB',
  'Intel i7-1165G7',
  'Intel Iris Xe',
  '13.3"',
  NULL,
  'Nightfall Black',
  'Dnipro',
  6,
  'Convertible 2-in-1 with OLED display and premium finish.',
  ARRAY[
    'https://placehold.co/600x600/png?text=HP+Spectre+x360',
    'https://placehold.co/600x600/png?text=HP+Spectre+x360+Tablet'
  ],
  true,
  3,
  4.4,
  41
),
(
  'Acer Aspire 7',
  'acer-aspire-7',
  'laptops',
  'Acer',
  'Aspire 7',
  17900,
  NULL,
  'UAH',
  'C',
  '512GB',
  '8GB',
  'Intel i5-10300H',
  'NVIDIA GTX 1650',
  '15.6"',
  NULL,
  'Black',
  'Kharkiv',
  1,
  'Affordable gaming laptop with visible wear on chassis.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Acer+Aspire+7',
    'https://placehold.co/600x600/png?text=Acer+Aspire+7+Side'
  ],
  true,
  6,
  4.1,
  27
),
(
  'iPad Air 4 64GB',
  'ipad-air-4-64gb',
  'tablets',
  'Apple',
  'iPad Air 4',
  16900,
  19900,
  'UAH',
  'B',
  '64GB',
  NULL,
  'Apple A14',
  NULL,
  '10.9"',
  NULL,
  'Sky Blue',
  'Kyiv',
  3,
  'Lightweight tablet with excellent screen and Apple Pencil support.',
  ARRAY[
    'https://placehold.co/600x600/png?text=iPad+Air+4',
    'https://placehold.co/600x600/png?text=iPad+Air+4+Back'
  ],
  true,
  4,
  4.6,
  39
),
(
  'Samsung Galaxy Tab S8',
  'samsung-galaxy-tab-s8',
  'tablets',
  'Samsung',
  'Galaxy Tab S8',
  21500,
  24900,
  'UAH',
  'A',
  '128GB',
  '8GB',
  'Snapdragon 8 Gen 1',
  NULL,
  '11"',
  NULL,
  'Graphite',
  'Lviv',
  6,
  'High-end Android tablet with S Pen and 120Hz display.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Galaxy+Tab+S8',
    'https://placehold.co/600x600/png?text=Galaxy+Tab+S8+Back'
  ],
  true,
  2,
  4.7,
  22
),
(
  'Lenovo Tab P11',
  'lenovo-tab-p11',
  'tablets',
  'Lenovo',
  'Tab P11',
  8900,
  NULL,
  'UAH',
  'B',
  '128GB',
  '4GB',
  'Snapdragon 662',
  NULL,
  '11"',
  NULL,
  'Slate',
  'Odesa',
  1,
  'Great value tablet for media and browsing.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Lenovo+Tab+P11',
    'https://placehold.co/600x600/png?text=Lenovo+Tab+P11+Back'
  ],
  true,
  6,
  4.3,
  18
),
(
  'iPad mini 6 256GB',
  'ipad-mini-6-256gb',
  'tablets',
  'Apple',
  'iPad mini 6',
  19900,
  22900,
  'UAH',
  'A',
  '256GB',
  NULL,
  'Apple A15',
  NULL,
  '8.3"',
  NULL,
  'Purple',
  'Dnipro',
  6,
  'Compact tablet in excellent condition, perfect for travel.',
  ARRAY[
    'https://placehold.co/600x600/png?text=iPad+mini+6',
    'https://placehold.co/600x600/png?text=iPad+mini+6+Back'
  ],
  true,
  3,
  4.8,
  33
),
(
  'Anker 20W USB-C Charger',
  'anker-20w-usb-c-charger',
  'accessories',
  'Anker',
  'Nano 20W',
  550,
  NULL,
  'UAH',
  'A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'White',
  'Kyiv',
  3,
  'Compact fast charger, barely used.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Anker+20W+Charger'
  ],
  true,
  15,
  4.7,
  56
),
(
  'Apple MagSafe Charger',
  'apple-magsafe-charger',
  'accessories',
  'Apple',
  'MagSafe Charger',
  1050,
  NULL,
  'UAH',
  'B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'White',
  'Lviv',
  1,
  'Genuine MagSafe charger with minor cosmetic wear.',
  ARRAY[
    'https://placehold.co/600x600/png?text=MagSafe+Charger'
  ],
  true,
  10,
  4.5,
  41
),
(
  'Logitech MX Master 3',
  'logitech-mx-master-3',
  'accessories',
  'Logitech',
  'MX Master 3',
  2150,
  2590,
  'UAH',
  'B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Graphite',
  'Kyiv',
  3,
  'Ergonomic wireless mouse in great condition.',
  ARRAY[
    'https://placehold.co/600x600/png?text=MX+Master+3'
  ],
  true,
  8,
  4.8,
  73
),
(
  'Samsung T7 1TB SSD',
  'samsung-t7-1tb-ssd',
  'accessories',
  'Samsung',
  'T7',
  2900,
  NULL,
  'UAH',
  'A',
  '1TB',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Blue',
  'Odesa',
  6,
  'Fast portable SSD with USB-C cable included.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Samsung+T7+SSD'
  ],
  true,
  9,
  4.7,
  48
),
(
  'PlayStation 5 Digital Edition',
  'playstation-5-digital-edition',
  'gaming',
  'Sony',
  'PS5 Digital',
  19900,
  22900,
  'UAH',
  'B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'White',
  'Kyiv',
  3,
  'Console only, works perfectly. Includes one controller.',
  ARRAY[
    'https://placehold.co/600x600/png?text=PS5+Digital'
  ],
  true,
  4,
  4.9,
  120
),
(
  'Xbox Series X',
  'xbox-series-x',
  'gaming',
  'Microsoft',
  'Xbox Series X',
  20500,
  NULL,
  'UAH',
  'A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Black',
  'Lviv',
  6,
  'Excellent condition, minimal usage, includes controller.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Xbox+Series+X'
  ],
  true,
  3,
  4.8,
  95
),
(
  'Nintendo Switch OLED',
  'nintendo-switch-oled',
  'gaming',
  'Nintendo',
  'Switch OLED',
  13900,
  15900,
  'UAH',
  'B',
  '64GB',
  NULL,
  NULL,
  NULL,
  '7"',
  NULL,
  'White',
  'Dnipro',
  3,
  'Great condition with small marks on dock.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Switch+OLED'
  ],
  true,
  5,
  4.7,
  68
),
(
  'Razer Kraken V3 Headset',
  'razer-kraken-v3-headset',
  'gaming',
  'Razer',
  'Kraken V3',
  2400,
  NULL,
  'UAH',
  'B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Black',
  'Kyiv',
  1,
  'Comfortable gaming headset with strong bass.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Razer+Kraken+V3'
  ],
  true,
  7,
  4.4,
  33
),
(
  'AirPods Pro (2nd Gen)',
  'airpods-pro-2nd-gen',
  'audio',
  'Apple',
  'AirPods Pro 2',
  7200,
  8600,
  'UAH',
  'B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'White',
  'Kyiv',
  6,
  'Active noise cancelling works great, includes case.',
  ARRAY[
    'https://placehold.co/600x600/png?text=AirPods+Pro+2'
  ],
  true,
  6,
  4.8,
  140
),
(
  'Sony WH-1000XM4',
  'sony-wh-1000xm4',
  'audio',
  'Sony',
  'WH-1000XM4',
  8900,
  10900,
  'UAH',
  'B',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Black',
  'Lviv',
  6,
  'Top-tier noise cancelling headphones with long battery life.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Sony+WH-1000XM4'
  ],
  true,
  4,
  4.9,
  84
),
(
  'JBL Flip 6',
  'jbl-flip-6',
  'audio',
  'JBL',
  'Flip 6',
  3200,
  NULL,
  'UAH',
  'A',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Blue',
  'Odesa',
  3,
  'Portable Bluetooth speaker, excellent condition.',
  ARRAY[
    'https://placehold.co/600x600/png?text=JBL+Flip+6'
  ],
  true,
  9,
  4.6,
  29
),
(
  'LG UltraFine 27-inch 4K',
  'lg-ultrafine-27-4k',
  'monitors',
  'LG',
  'UltraFine 27',
  15800,
  18900,
  'UAH',
  'B',
  NULL,
  NULL,
  NULL,
  NULL,
  '27"',
  NULL,
  'Black',
  'Kyiv',
  6,
  'Sharp 4K panel with USB-C connectivity.',
  ARRAY[
    'https://placehold.co/600x600/png?text=LG+UltraFine+27'
  ],
  true,
  3,
  4.5,
  26
),
(
  'Dell S2721DGF 27-inch QHD',
  'dell-s2721dgf-27-qhd',
  'monitors',
  'Dell',
  'S2721DGF',
  13900,
  NULL,
  'UAH',
  'B',
  NULL,
  NULL,
  NULL,
  NULL,
  '27"',
  NULL,
  'Black',
  'Lviv',
  3,
  'Fast QHD gaming monitor with 165Hz refresh rate.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Dell+S2721DGF'
  ],
  true,
  5,
  4.6,
  31
),
(
  'Samsung Odyssey G5 32-inch',
  'samsung-odyssey-g5-32',
  'monitors',
  'Samsung',
  'Odyssey G5',
  14900,
  16900,
  'UAH',
  'B',
  NULL,
  NULL,
  NULL,
  NULL,
  '32"',
  NULL,
  'Black',
  'Dnipro',
  3,
  'Curved 144Hz monitor, great for immersive gaming.',
  ARRAY[
    'https://placehold.co/600x600/png?text=Samsung+Odyssey+G5'
  ],
  true,
  4,
  4.4,
  24
);
